Multiple admins, mark not registered users
Bostonhacks/headstart pull request #50
Opened 2017-10-01 20:27 UTC by KenG98

Admin page now marks which users have registered with MLH and which users haven't. The website also now allows multiple administrator emails as such:

* in the .env instead of 
ADMIN_EMAIL=email1
* write
ADMIN_EMAIL=email1,email2,email3

This way we can all have access to the admin panel and accept/reject applicants.

2017-10-01 23:27 UTC, lkwatson approved these changes
All looks good, thank you Ken. 

@agoncharova or @a--hoang can you review and merge.

2017-10-03 00:14 UTC, anna1go requested changes
Added a couple of comments, mostly nitpicks. Thanks for doing this!

2017-10-03 00:14 UTC, agoncharova commented on bin/www
> + * Separate admin emails into a list of emails.
Use // for single line comments

2017-10-03 00:14 UTC, agoncharova commented on bin/www
> +
👾👾 (space invader; :nit: too much space)

2017-10-03 00:14 UTC, agoncharova commented on views/pages/admin-console.ejs
> +          <td v-if='user.status != "Not Attending" && user.local.registered != false' style="min-width:150px">
We could probably avoid using the double negative:
`!= false -> == true`

2017-10-03 13:09 UTC, merged